name: build-app
on: [push]
jobs:
  yarn-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '15'
      - run: yarn install
      - run: yarn build 
      # this might need --frozen-lockfile but it seems to break build
      # TODO add this when we fixed the builds in genreal

  bump-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.output.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
      - id: setversion
        uses: codacy/git-version@2.4.0
        name: Git Version
        with:
          release-branch: chain4travel
          dev-branch: dev
      - id: output
        run: echo "::set-output name=version::${{ steps.setversion.outputs.version }}"

  tag-commit:
    runs-on: ubuntu-latest
    needs: bump-version
    if: github.ref == 'refs/heads/chain4travel'
    steps:
      - uses: actions/checkout@v3
      - name: Create Git tag
        uses: actions/github-script@v4
        with:
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ needs.bump-version.outputs.version }}",
              sha: context.sha
            })
  docker-build:
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        name: Login to DockerHub
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_pass }}
      - name: Set tag variables
        id: setTagVariables
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          if [[ "${{ github.ref_name }}" == "chain4travel" ]]; then
              echo "::set-output name=stable::c4tplatform/camino-wallet:stable"
          fi
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
              echo "::set-output name=stable::c4tplatform/camino-wallet:dev"
          fi
          echo "::set-output name=branch::c4tplatform/camino-wallet:${BRANCH_NAME////-}-${{ github.run_id }}"
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: |
            ${{ steps.setTagVariables.outputs.branch }}
            c4tplatform/camino-wallet:${{ needs.bump-version.outputs.version }}
            ${{ steps.setTagVariables.outputs.stable }}
          push: ${{ github.ref == 'refs/heads/chain4travel' || github.ref == 'refs/heads/dev' }}