name: docker

on:
  push:
    tags:
      - v*
    branches: [chain4travel, dev]
  workflow_dispatch:
    inputs:
      wd_branch:
        description: 'camino-wallet branch'
        required: true
        default: 'dev'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '15'
      - id: branchVars
        name: Evaluate branch
        run: |
          if [[ ${{ github.event_name }} != workflow_dispatch ]]; then
            echo "branch=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          else
            echo "branch=${{ github.event.inputs.wd_branch }}" >> $GITHUB_OUTPUT
          fi
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.branchVars.outputs.branch }}
          fetch-depth: 0
      - uses: docker/login-action@v2
        name: Login to DockerHub
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_pass }}
      - name: Set tag variables
        id: setTagVariables
        run: |
          echo "version=$(git describe)" >> $GITHUB_OUTPUT
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          context: ./
          tags: |
            c4tplatform/camino-wallet:${{ steps.setTagVariables.outputs.version }}
          push: ${{ github.ref == 'refs/heads/chain4travel' || github.ref == 'refs/heads/dev' }}
