name: update-gcs-bucket

on:
  push:
    branches:
        - c4t
        - dev
        - suite

env:
  node_version: 16

jobs:
  build_deploy_scrape:    
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare variables
        id: prepareVariables
        run: |
          DOMAIN="suite-wallet.camino.network"
          echo "prodBucket=$DOMAIN" >> $GITHUB_OUTPUT
          if [[ "${{ github.ref }}" == "refs/heads/c4t" ]]; then
              echo "bucket=stage.$DOMAIN" >> $GITHUB_OUTPUT
              echo "build_env=stage" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
              echo "build_env=dev" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/suite" ]]; then
              echo "build_env=dev" >> $GITHUB_OUTPUT
          fi

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          
      - name: Install yarn dependencies        
        run: yarn install

      - name: Build
        run: yarn build:${{ steps.prepareVariables.outputs.build_env }}

      - name: Cloud authentication
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Update Bucket
        if: ${{ github.ref == 'refs/heads/c4t' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/suite' }}
        run: |
          gsutil -m rsync -J -R -d dist gs://${{ steps.prepareVariables.outputs.bucket }}